# Database Connection Settings
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pkojfrfbevsuzrysgpkw
spring.datasource.password=@Benolirao1705
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#GOOGLE OAUTH
spring.security.oauth2.client.registration.google.client-id=389343386637-r85hkfkr81el5ea4guonb7f4l9a9vlv9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email